### ISSUE TITLE
Make schedules / calendars printable (add print button)

### ISSUE THREAD

**Issue by Ghosts** [Burgundy-Labs/TimeSlot#176]

**Comment by Pinjasaur** [comment]
I assume this would be a button that calls `window.print()`? Could couple with a print stylesheet (e.g. `@media print {}` as well.

**Comment by Ghosts** [comment]
Yeah that's what I'm thinking. The good news is I **believe** FullCalendar has options for print styling built-in, we'd just have to add some SASS to ensure images are formatted properly for printing, etc.
