### ISSUE TITLE
Enable HTTPS for Docker image routing

### ISSUE THREAD

**Issue by Ghosts** [Burgundy-Labs/TimeSlot#189]
https://devsidestory.com/lets-encrypt-with-docker/

**Comment by FoamCactus** [comment]
This works in the docker branch. Hard to really demo though, it requires a dns record to point to the server.

**Comment by Ghosts** [comment]
What would we need to change / run to deploy it with https on prod?

**Comment by FoamCactus** [comment]
basically we have to fill in the domain name in a config file and then start the stack.
